### ISSUE TITLE
Add pdsf as 'Decompiler'

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1037]
the print disasm summary is pretty useful in many situations, would be good to have it in the decompiler tab, so we can see an overview of the strings and calls done in he function by just clicking them in the functions widget.

`pdsf@e:scr.html=0`

**Comment by radare** [comment]
Btw, the pseudocode widget doesnt updates like the disasm one does. maybe we want to have that in the case we are seeking to a different function. I understand this may be a performance issue in some situations..

**Comment by ITAYC0HEN** [comment]
We have it shown when you hover a function with your cursor in the Functions widget. We have a general summary, a disassembly preview and a function summary (calls, strings, etc.)

We dont have place for all so we truncated it in order to keep it more readable:

![image](https://user-images.githubusercontent.com/20182642/50496327-4b06fa80-0a2f-11e9-856b-58d265ea4a2e.png)

**Comment by ITAYC0HEN** [comment]
feature exists in a tooltip for every function. Closing
