### ISSUE TITLE
Add right click apply structure in the disassembly

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1073]

**Comment by m0nk3ydluffy** [comment]
Hey! Are you talking about the `tp  <type> [addr|varname]` command of r2? And could you please elaborate how would you like it to be implemented. For example, do we give the "apply structure" option in the disassembly context menu or types context menu or both. And where should the result be displayed?

**Comment by ITAYC0HEN** [comment]
This needs a good plan and a thorough discussion indeed.

To answer it quickly, similar to IDA just cooler:
Right click on an Immediate value >> Structure Offset >> choose struct (with previews)

![image](https://user-images.githubusercontent.com/20182642/53180037-83752000-35fd-11e9-9d10-db9163ad1154.png)



In radare2 you can use the `tas` command to see candidates for a given immediate, and the `ta <type> @ <addr>` command to apply struct.


Here is an example for you:

```
# Open radare2 on 32bit mode
$ r2 -b 32 -

# write the following bytes for the example
[0x00000000]> wx 648b35300000008b760c8b761c8b46088b7e208b36

# disassemble 5 instructions
[0x00000000]> pd 5
            0x00000000      648b35300000.  mov esi, dword fs:[0x30]    
            0x00000007      8b760c         mov esi, dword [esi + 0xc]  
            0x0000000a      8b761c         mov esi, dword [esi + 0x1c]
            0x0000000d      8b4608         mov eax, dword [esi + 8]   
            0x00000010      8b7e20         mov edi, dword [esi + 0x20]

# Load an header file containing structs
[0x00000000]> to /tmp/test.h 

# List the loaded structs
[0x00000000]> ts
_EPROCESS
_EPROCESS_VALUES
_LDR_DATA_TABLE_ENTRY
_LIST_ENTRY
_PEB
_PEB32
_PEBS_DS_SAVE_AREA
_PEB_LDR_DATA
_PEB_LDR_DATA32
_UNICODE_STRING

# all matching structure offsets to a given immediate
[0x00000000]> tas 0xc
_EPROCESS.Flags2
_LDR_DATA_TABLE_ENTRY.InMemoryOrderLinks.Blink
_PEB.ImageBaseAddress
_PEB32.Ldr
_PEB_LDR_DATA32.InLoadOrderModuleList

# Apply the chosen struct a the given address
[0x00000000]> ta _PEB32.Ldr @ 0x7

# same for 0x1c
[0x00000000]> tas 0x1c
_LDR_DATA_TABLE_ENTRY.EntryPoint
_PEB.ProcessHeap
_PEB32.FastPebLock
_PEB_LDR_DATA32.InInitializationOrderModuleList

# Apply it
[0x00000000]> ta _PEB_LDR_DATA32.InInitializationOrderModuleList @ 0xa

# Print results
[0x00000000]> pd 5
            0x00000000      648b35300000.  mov esi, dword fs:[0x30]    
            0x00000007      8b760c         mov esi, dword [esi + _PEB32.Ldr]  
            0x0000000a      8b761c         mov esi, dword [esi + _PEB_LDR_DATA32.InInitializationOrderModuleList] 
            0x0000000d      8b4608         mov eax, dword [esi + 8]    
            0x00000010      8b7e20         mov edi, dword [esi + 0x20]

````

**Comment by m0nk3ydluffy** [comment]
Hey @ITAYC0HEN . That was a wonderful explanation. Thanks a lot for clearing this up. I was completely heading in the wrong direction. I'll work on this.

**Comment by ITAYC0HEN** [comment]
I forgot to upload the header file but I think you should have it since I sent it to you.

Also, note that this is just a single use for applying Struct. You should also be able to do this on variables and on data (non instructions) 

Check out the r2book chapter about types and structs

**Comment by m0nk3ydluffy** [comment]
> I forgot to upload the header file but I think you should have it since I sent it to you.

Yes I have that header file.

> Also, note that this is just a single use for applying Struct. You should also be able to do this on variables and on data (non instructions)
Check out the r2book chapter about types and structs

Yep! Will do.

**Comment by AlexKornitzer** [comment]
So @ITAYC0HEN asked me to chime in here with some thoughts as I added the offset support to the `ta` command, whether they will be useful is another thing.

Currently I think mirroring what ida does is sufficient for an initial implementation (context menu & filterable pop up window) as I don't see a massive need for bells and whistles. From an implementation point of view if we ignore pointer offsets (i.e. assume all pointers to a struct start at its base - https://github.com/radare/radare2/pull/12322) then implementing this should be trivial. 

Now the problem of `tas` offsets - if we approach this from a manual point of view then can just add an option to the pop up and/or context menu to allow the setting of the offset value for `ta(s)`, once specified cutter would then run `ta(s)` with the offset rather than from the base. From an automatic point of view ideally `tas` would iterate over a structure checking is viability by validating alignment, this would have to be implemented in r2 core so is most likely out of scope. Although my concern about this is that it could produce too much junk output if we have very view alignment errors, it may be that usage of offsets is so rare that the manual option is sufficient.

Hopefully that makes sense, I can add some examples if required.

**Comment by m0nk3ydluffy** [comment]
Hey @AlexKornitzer ! Thanks for the insight. As you said, I'll try to mirror IDA for now. And maybe later when I'm more comfortable, I'll try to work out a way for the structs whose pointers are not pointing to the beginning.

**Comment by ITAYC0HEN** [comment]
Thank you Alex! 


Gaurav, IDA supports it already and much more behind the scenes, so you can't really mirror what IDA currently have with the current situation in r2. But yeah, only the basics should work for now 😊

**Comment by m0nk3ydluffy** [comment]
Pardon my ignorance. I didn't know that IDA supports that. I guess I'll be implementing only the very basics then.

**Comment by AlexKornitzer** [comment]
Ah my bad on the terming of mirroring then, meant that of the image above, haven't used IDA in a while :P
