### ISSUE TITLE
Fix logo color not changing when switching theme

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#1161]

**Comment by ITAYC0HEN** [comment]
can't reproduce.
I think that what happened is that you had an old config, without my new config-item (which indicates first execution), and the new version of Cutter parsed it and understood two things
1. You have dark theme (old config was set to dark)
2. This is the first time you execute Cutter, because my config-item wasn't in the configuration

**Comment by xarkes** [comment]
I will try again to confirm the issue :)

**Comment by xarkes** [comment]
I could not reproduce it.
