### ISSUE TITLE
asm.stackptr breaks if you scroll too much in the disassembly widget

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#1282]
**Environment information**
* Operating System:
* Cutter version:
* File format:

**Describe the bug**

`asm.stackptr` value becomes to 0 if you scroll too much in the disassembly widget.

**To Reproduce**

1. Enable `asm.stackptr` in the disas options
2. Go to the disassembly widget
3. Scroll a bit
4. If the original value that should be propagated through the function is different than 0 and comes out of the screen, the new stackptr becomes 0 for the rest of the function.

**Expected behavior**

Keep in memory somewhere (radare2, Cutter, ...?) the base ptr.

**Screenshots**

First view on the function:
![image](https://user-images.githubusercontent.com/10772605/54149149-d6d8d200-4435-11e9-8c3a-3914c35c6823.png)

After scrolling down:
![image](https://user-images.githubusercontent.com/10772605/54149189-e7894800-4435-11e9-9fc7-ce9b4008b854.png)

As you can see, everything became wrong.

**Comment by ITAYC0HEN** [comment]
Does it happen in r2 as well?

**Comment by radare** [comment]
thats because you need to disassemble from the begining of the function to get the right output, that wont happen if cutter caches the data and handles it by itself instead of disassembling every offset randomly, same happens with asm.emu, and thats even worst because without recursive emulation you cant get the right pointers and nothing makes sense. that why graph view is so important because it caches and does recursive emulation. we have commands to cache some recursive emulation analysis results as comments as a workaround, but i guess that after fixing the maxbb pr i should probalby go improve that stuff and start computing the stackptr and emu from the begining of the function instead of the begining of the place u start to disasm

**Comment by radare** [comment]
i would probably prefer to move the issue to r2

**Comment by a1ext** [comment]
good catch

**Comment by radare** [comment]
well, its known issue :) we may probably abuse anal hints to save this data, or maybe inside each basic block cache the value of the stackptr, in case it can be reached only from 1 path

**Comment by a1ext** [comment]
this means it will take extra more memory...

**Comment by xarkes** [comment]
Example with Graph:
![image](https://user-images.githubusercontent.com/10772605/54289731-f7299d80-45a9-11e9-8c11-480e45c13cb8.png)

**Comment by xarkes** [comment]
Should we remove the option for now since it's broken?

**Comment by radare** [comment]
I didnt said stackptr is recursive in the graph. Only asm.emu is
