### ISSUE TITLE
RFE: Improvements in Graph

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1342]
* [ ] Support pds instead of pd in the nodes
* [ ] Honor tracing information (see dt) to highlight the executed nodes, .. dup of 1272
* [ ] Support folding nodes
* [ ] Support 1 level refs/xrefs graphs
* [ ] List of basic blocks in columns (offset, name, calls, output nodes, ...) on click seek to them (inspired by https://github.com/radare/radare2/issues/13403)
* [ ] pinch to zoom (or shift+wheel)
* [ ] support background gradients instead of flat color :?

**Comment by Maijin** [comment]
* [ ] Support pds instead of pd in the nodes *dup of 1374*
* [ ] Honor tracing information (see dt) to highlight the executed nodes, .. *dup of 1272*
* [ ] Support folding nodes *dup of 1270*
* [ ] Support 1 level refs/xrefs graphs *dup of 1375*
* [ ] List of basic blocks in columns (offset, name, calls, output nodes, ...) on click seek to them (inspired by https://github.com/radare/radare2/issues/13403) *dup of 1376*
* [ ] pinch to zoom (or shift+wheel) *dup of 1377*
* [ ] support background gradients instead of flat color :? *dup of 1378*
