### ISSUE TITLE
Add pinch to zoom

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1377]
**Is your feature request related to a problem? Please describe.**

Ability to pinch to zoom (or shift+wheel) is missing in Cutter.
From @trufae  

**Describe the solution you'd like**

Add ability to pinch to zoom (or shift+wheel) is missing in Cutter

**Comment by AntonReborn** [comment]
@Maijin @trufae can you describe the difference in behaviors between the current zooming using Ctrl+wheel and requested "Pinch"?

**Comment by ITAYC0HEN** [comment]
Both pinch zoom (on laptop mouse pad) and <kbd>Ctrl</kbd>+Wheel works for me.
What did you experience?

**Comment by trufae** [comment]
Control+wheel works for you because you are not using a Mac. that's why im requesting this, because mac users use control+- to zoom, because ctrl+wheel does nothing, also, ctrl+wheel in mac is usually a system-wide zoom for accessibility. Also, pinch to zoom is pretty common and human friendly way to zoom in/out and used by many apps in the Mac ecosystem and well described in the HIG. so not sure which other reasons you need :)

**Comment by ITAYC0HEN** [comment]
So is this a macOS-only issue? Because pinching the mouse-pad on my laptop works both for windows and Linux. If so, need to tag it as Mac only

**Comment by a1ext** [comment]
For reference [link](https://doc.qt.io/qt-5/qnativegestureevent.html)
