### ISSUE TITLE
Scrolling to void in the graph

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1459]
open graph, wheel around. no way to find any bb anymore.

will be good to have a key like '.' to scroll the last selected bb, or "the closest one" otherwise on big graphs, without minigraph is pretty easy to get lost

**Comment by radare** [comment]
(or not allow to scroll around places where there are no nodes)

**Comment by xarkes** [comment]
We decided to have this behaviour as far as I remember, see this issue: https://github.com/radareorg/cutter/issues/727

Now there can surely be improvements, but that's why we have an overview widget, you just have to click on it to get back to the graph!

**Comment by ITAYC0HEN** [comment]
or seek to it again, using the Functions widget or the go-to textbox

**Comment by karliss** [comment]
It is already possible to press j/k for moving up/down in current bb which will also bring it to the center of screen.

Without reverting #727 scrolling could be limited so that right side of screen can't go further than left side of image, the same for other directions. At that point picture is only barely outside the screen which is furthest towards void anyone could need. This doesn't solve the case of large white spots somewhere in the middle of graph.

**Comment by ITAYC0HEN** [comment]
Closed via  #1467
