### ISSUE TITLE
It is possible to disassemble a running process?

### ISSUE THREAD

**Issue by pangqingyuan1991** [radareorg/cutter#1580]
**Is your feature request related to a problem? Please describe.**

Some program will encrypt/pack itself using tool like upx, so it is useless to analyse the executable file directly.  Is it possible to disassemble memory block of a running process?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pangqingyuan1991** [comment]
For example, I can use such code to load my real program. The user can never touch my program file content if I add encryption.
`#define _GNU_SOURCE 
#include <sys/mman.h>
#include <unistd.h>
#include <stdint.h>
#include <sys/syscall.h>
#include <fcntl.h>
#include <stdio.h>

extern uint8_t foo_data[]      asm("_binary_htop_start");
extern uint8_t foo_data_size[] asm("_binary_htop_size");
extern uint8_t foo_data_end[]  asm("_binary_htop_end");
int main(int argc, char **argv, char **env)
{
    int exefd = memfd_create("", MFD_CLOEXEC);
    printf("%p %d %ld\n", foo_data, exefd, write(exefd, foo_data, foo_data_end-foo_data));
    char * const vv[] = {"htopp", NULL};
    //execveat(exefd, NULL, vv, NULL, AT_EMPTY_PATH);
    exefd = syscall(__NR_execveat, exefd, "", vv, env, AT_EMPTY_PATH);
    perror("");
    return 0;
}
`

**Comment by ITAYC0HEN** [comment]
This is not possible at the moment since Cutter does not support Debugging. That said, you can use emulation and radare2 to unpack UPX packed samples for example. This will not work in Cutter but we wish to implement debugging as soon as we can.

For more questions, please refer to our community groups on Telegram and IRC:
https://t.me/r2cutter
https://t.me/radare
