### ISSUE TITLE
Support R2 Themes

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#160]
Right now Cutter only have UI themes. this is dark and light.

But r2 have a large list of themes that can be accessed via `eco` command. we can change that from the console, but the UI have no menu entry for this. I would add this in the app menubar

**Comment by xarkes** [comment]
So we decided not to do this because radare2 doesn't support truecolor (3-4 bytes). So sometimes the colors are very very bad and unreadable for most themes. If someone refactor the color handling of radare2, maybe we can consider doing this again. But not for now imo.

**Comment by radare** [comment]
R2 supports true color already. If the colors look bad its user fault to set the wrong theme. Same issue happens with all other gui apps if u choose the wrong colorscheme

**Comment by radare** [comment]
At least ogray and pink themes should be available :p maybe i can tag at r2 level the themes to be used for light and dark modes

**Comment by xarkes** [comment]
Nah you don't understand. The way radare stores the color value is with the ascii code (wtf?). Even if you use truecolor, it would take that ascii code and convert it to truecolor. Anyway I already spent many hours on this, and the way it is currently implemented in radare2 is not usable for any third party app. Because then ecc, ecj are broken, not cross platform, etc. Too many issues.

**Comment by xarkes** [comment]
So imho the best way would be to refactor radare so it handles true colors.

**Comment by radare** [comment]
Ansi escapes codes support rgb encoding with 2 bytes per color

**Comment by xarkes** [comment]
Cf this issue: https://github.com/radareorg/cutter/issues/63

**Comment by radare** [comment]
Already does. But yep it can be imrpoved. Did you saw the out of the themes in css format?

**Comment by Maijin** [comment]
same issue

**Comment by xarkes** [comment]
Yes I saw it and it's not portable (doesn't work properly on Windows).

**Comment by Maijin** [comment]
It's a r2 issue shouldn't be open here.

**Comment by xarkes** [comment]
Yes and no, I mean what should we do?

**Comment by ishitatsuyuki** [comment]
The experience I had with r2 themes so far is that it doesn't work well with custom terminal color schemes (it seems to enforce absolute color instead of one of the pallette). I think we can invent our own pallette system for Cutter here.

**Comment by Maijin** [comment]
or fix r2

**Comment by XVilka** [comment]
@ishitatsuyuki @Maijin this happens when you use "truecolor" mode, which sets the colors directly in RGB format. Thats the point of this mode - to look the same everywhere. If you stick with the palettes, use less color resolution, but it's being "legacy" mode, see more at https://gist.github.com/XVilka/8346728

**Comment by xarkes** [comment]
Yes but there is an issue where Windows does not behave the same when truecolor is activated. And so some colors are incorrectly parsed

**Comment by xarkes** [comment]
I think the way it works for now is okayish. My opinion is that we should have our own themes. Might sound stupid but I don't want to refactor the colors in radare2.
