### ISSUE TITLE
Small graph window hides fcnsign with horizontal scrollbar

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#1623]
<img width="366" alt="Screenshot 2019-06-25 at 17 49 47" src="https://user-images.githubusercontent.com/6431515/60113255-aa8d5b00-9771-11e9-9eb3-73f39471c3a6.png">

**Comment by ITAYC0HEN** [comment]
Thanks!
Just to clarify for whoever solve it -- the scrollbar should be therem but shouldn't cover the text in height. Need to make the box a bit taller

**Comment by karliss** [comment]
It would be good to change the layout of widget so that function  name isn't inside graph view. Probably add some kind of vertical layout and move it from disasemblerGraphView to GraphWidget.

Current code abuses the fact drawing are is scroll area and puts stuff inside it. This causes ugly hack like `HEADER_HEIGHT` in GrapView and sometimes causes 1px part of graph being visible above header. This

**Comment by ITAYC0HEN** [comment]
much better! +1
