### ISSUE TITLE
agC Global callgraph, but with cutters graph engine

### ISSUE THREAD

**Issue by zeroeth** [radareorg/cutter#1776]
I really like cutters overview and graph views for functions.

It would be super useful to have an interactive version of the agC command to help spelunk overall code organization of a binary!

How easy would it be to tap into the whole family of ag* graph commands and provide native cutter views for them?

**Comment by karliss** [comment]
Yes that's one of missing features. There is already #406. As you said all r2 graphs should be supported. Nothing too complicated just needs some work.

**Comment by zeroeth** [comment]
Ah didn't turn up in my search thanks! Btw I've been importing the graphs into Gephi for analysis using their different layout engines for clustering the call graph and sizing/coloring nodes based on neighborhood statistics.

If the call graphs got implemented in cutter, would it be easy to augment with features like that via plugin?

example:

<img width="625" alt="gephi callgraph" src="https://user-images.githubusercontent.com/5617/64914683-03361980-d70b-11e9-9fc0-c99603b719b0.png">

**Comment by karliss** [comment]
I was going to answer no but after considering it the answer is maybe.

It is questionable if the builtin support for call graph in Cutter would make it significantly easier to create such plugin. Reading the json graph description from r2 is easy part. Node drawing code and clustering layout engine would have to be implemented by plugin. Although it would be nice if it could reuse parts like context or image export.

It would make it easier to create such view inside Cutter as non plugin. There are already some Graphviz based layouts and Graphviz has some builtin clustering layouts maybe those could be used. They might not be as good Gephi but probably better than self made stuff and would require minimal effort for implementing.

If you really want to use Gephi as layout engine it would be better done as plugin due to requiring additional external dependency. It might need some minor tweaks in the Cutter graph code to allow modifying all the required places.


Current structure is something like this
XGraphDock -> XGraphView -- GraphView -> GraphLayout
responsibilities are:
* XGraphDock -> contains XGraphView and any additional UI elements. Some high level interaction logic with rest of cutter for when to display what. It should be possible to create custom dock widget from plugin.
* XGraphView -> GraphView that displays graph X. Retrieves the logical graph data from r2.  Implements X specific drawing of a single node and reacts to clicking on them. Should be implementable from plugin.
* GraphView -> base class for all GraphView.  Decides what blocks need to be drawn, when a block was clicked.
* GraphLayout - graph layout engine performs placement of nodes and edge routing. As input receives node sizes and list of edges.   The interface for making custom layouts engines is there but GraphView currently doesn't allow setting them. Need to add a method for setting and getting arbitrary layout engine instance. Currently there is only `GraphView::setGraphLayout(graphLayoutEnum)`. That would be also helpful to allow custom GraphView to query layout engine for any other properties calculated during layout.

**Comment by zeroeth** [comment]
Thanks for discussing the plausibility! And yes graphviz is great too.

My thinking is mostly around having an interactive visual search. With actions like 'size or color gradient by # of branches, lines of code, or jumps, or memory address' all those things we can look at in the function list.

The clustering layout itself doesn't even need to be super robust, just to help strengthen the view of strongly connected functions.

Gephi itself is just a container for plugins. The real work is by different researchers layout algorithms like:

OpenOrd https://www.cs.otago.ac.nz/homepages/smartin/presentations/OpenOrd.pdf
Force Atlas 2 https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0098679
Yifan Hu http://yifanhu.net/PUB/graph_draw_small.pdf
