### ISSUE TITLE
scaling in graph mode

### ISSUE THREAD

**Issue by s0i37** [radareorg/cutter#178]
Nice work.
Could you please to add scaling in graph mode. Because some call-graphs is huge and it's not comfortable.

**Comment by gingerbeardman** [comment]
Cmd+/- zoom within limits would be nice, especially on retina display.

**Comment by thestr4ng3r** [comment]
I totally agree. Another use would be so you could dock the graph next to regular disassembly and zoom it out in order to have a mini-graph showing where in the control flow you currently are.

Not the highest priority at the moment, but definitely useful. And I am sure it would be appreciated to contribute the changes back to x64dbg.

**Comment by s0i37** [comment]
Cmd+/-  - dont work. I have a linux (awesome WM).
May be ctrl +/- like an IDA ?

**Comment by gingerbeardman** [comment]
Platform specific shortcut keys could help. So shortcut keys are as you'd expect on the host platform.
