### ISSUE TITLE
Comment doesn't update new variable name

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#1788]
**Environment information**
* Operating System: Parrot OS 4.7 x64
* Cutter version: 1.9.0
* File format: ELF

**Describe the bug**

When i changed variable name (the menu is still buggy, i changed it via retype variable), comment next to the instructor was use old name.
**To Reproduce**

1. Open binary file, now our `char * buf` should be defined as `char *s`
2. Comment next to instructor in any code is `s` 
3. Right click -> rename variable -> set to other name
4. Comment is still use `s` as variable name while the name in instructor is new name

**Expected behavior**

Comment should use new name as well

**Screenshots**
1. The name before edit (s2)
![Screenshot at 2019-09-24 23-00-45](https://user-images.githubusercontent.com/29118926/65528843-5126fa80-df1f-11e9-88eb-201d84f8026e.png)
2. Edit s2
![Screenshot at 2019-09-24 23-01-45](https://user-images.githubusercontent.com/29118926/65528845-51bf9100-df1f-11e9-9953-6a604eaeaa45.png)
3. New name is defined, comment still use s2
![Screenshot at 2019-09-24 23-01-52](https://user-images.githubusercontent.com/29118926/65528857-54ba8180-df1f-11e9-8b6c-24e1b7ff9e26.png)

**Additional context**

**Comment by nk521** [comment]
Hey! I had a look into this issue and turns out that this is just a simple confusion because of the same names (s1 and s2 in this case). The comments in pink you see are just the prototype names.

![image](https://user-images.githubusercontent.com/30789322/77112468-107fe800-6a4f-11ea-9d24-9527fd09a435.png)
Look at the synopsis section :)

Look at the third picture (that you posted), it clearly shows that `New_name` will be treated as `s2` and `string` as `s1` in `char *strcat(char *s1, const char *s2)`.

**Comment by ITAYC0HEN** [comment]
Thanks for the clarification! ':)
