### ISSUE TITLE
Running a program in debug mode will freeze Cutter

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1848]
**Environment information**
* Operating System: Arch Linux
* Cutter version: Recent Debug branch
* File format: Any

**Describe the bug**

While in debug mode, and clicking the Continue\Run button. The debugee is being executed and runnning. But the interface of Cutter itself froze and is not responsive.

**To Reproduce**

1. Open the Cutter binary in Cutter. Analyze quickly. you can stop the analysis in the middle
2. Start Debugging
3. Press the Continue button
4. See that the new Cutter (the debuggee) is running, but the interface of the original Cutter (the debugger) is not responsive.
5. Close the debuggee and see that the debugger is now back to be responsive

**Expected behavior**

The interface should keep being responsive

**Screenshots**

**Comment by ITAYC0HEN** [comment]
CC @yossizap @xarkes

**Comment by yossizap** [comment]
The reason is that the r2 continue commands are called with cmd() instead of the async command handler. Radare expects the user to send a signal using the keyboard for it to exit dbg_wait similarly to gdb, we can emulate this behavior with a button that will stop the currently selected thread by sending a signal to the async handler's pid. Some of the UI has to stay frozen though.

You can assign me to this issue, was planning on looking into it.
