### ISSUE TITLE
go to the end of file

### ISSUE THREAD

**Issue by andrewclarkii** [radareorg/cutter#1877]
Please add "Go to the end of file" In Disassembly window. I think it would be handy, especially when you have to "Set to Data" a couple of bytes from defined position to the end of a file. Also would be great if you implement this idea to "Set to Data" itself. For instance when user does not set number of items, then it should mean from "Start address" to the end of a file or implement a separate radio button for this in "Set to Data" window

**Comment by ITAYC0HEN** [comment]
Thank you for your ideas!
In the future, please separate the suggestion to different issues. This way we will be able to give better feedback.

> Please add "Go to the end of file" In Disassembly window

I am not sure it is usable enough to include it as a feature in Cutter. Currently, you can use simply seek to "$s" or to "entry0+$s" using the visual navigation text box at the top.

> Also would be great if you implement this idea to "Set to Data" itself. 

In my opinion, this is too risky since we don't have "undo". Pressing "Enter" will make all the following bytes as data and we don't want to take this risk.

**Comment by ITAYC0HEN** [comment]
I highly appreciate the issue you open and the time you invested in giving these suggestions. 
At this time, I would prefer to close this issue since these suggestions won't be implemented. You can always implement them as [plugins ](https://cutter.re/docs/plugins.html). 

Thank you again and please don't hesitate to open new issues with more ideas :)
