### ISSUE TITLE
Debugging doesn't work on files with spaces in their paths.

### ISSUE THREAD

**Issue by Satharus** [radareorg/cutter#2019]
**Environment information**
* Operating System: Arch Linux 
* Cutter version: 1.10-Linux
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format:

**Describe the bug**
When opening a file that has a space in its path, it works normally until you click on "Start Debug". It will cut the path at the first space and say that it doesn't have execute permissions.
If I give it the file: '/home/user/Documents/Executable Files/a.out'
It'll give me the following error: "File '/home/user/Documents/Executable' does not have executable permissions."

**To Reproduce**

1. Open Cutter
2. Open a file with a space in its path
3. Click on the green debug button at the top

**Expected behavior**

Cutter should debug the program normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/29730368/72553040-b4f37b80-38a0-11ea-99fc-ccef2c418140.png)

After clicking on debug, this happens:

![image](https://user-images.githubusercontent.com/29730368/72553058-bd4bb680-38a0-11ea-96b3-41f44daf27ea.png)

**Comment by ITAYC0HEN** [comment]
Thank you for your report and the time invested in writing it. We highly appreciate it!
Please notice that this issue was reported before and solved by our dear @yossizap :)

Issue: https://github.com/radareorg/cutter/issues/1961
Radare2 Fix: https://github.com/radareorg/radare2/pull/15697
Cutter FIX: https://github.com/radareorg/cutter/pull/1978
