### ISSUE TITLE
Don't show "Set as... -> String... -> Remove" where no string is defined

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#2059]
**Environment information**
* Operating System: Any
* Cutter version: Recent from Git
* Obtained from:
  - [x] Built from source
* File format: Any

**Describe the bug**

Currently, when right clicking a non-string instruction, there is the option to remove the definition of the instruction as string while it is actually a code. This shouldn't be available unless it is indeed defined as string/

**To Reproduce**

Right click on an instruction and see that "Set as... -> String... -> Remove" is available. 
![image](https://user-images.githubusercontent.com/20182642/74553964-1458b000-4f61-11ea-9850-303d6814bea0.png)

**Expected behavior**

The option to remove the definition of a String should only be there when the instruction is defined as string.

**Comment by dhaval0894** [comment]
Hi @ITAYC0HEN, I would like to give this a shot. Can you give me a bit of a headstart that how can I approach this?

**Comment by karliss** [comment]
Hi, here is general strategy for approaching your first issues:


I don't know your experience level so don't mind if some of the steps seem obvious.

*  Start by reading this https://cutter.re/docs/code.html
*  See https://github.com/radareorg/cutter/blob/master/docs/source/building.rst for compilation instructions
*  Get the build working
*  Run cutter and get familiar with how the menu behaves currently
*  Find the the source files implementing it, (practice searching code in your editor, this is an important skill)
*  ~~If necessary read https://doc.qt.io/qt-5/model-view-programming.html for basic understanding of how Qt model system works.~~ not required in this issue.
* Check if any of the existing code implements similar behavior in the same widget or similar widgets. If you do copy an existing code consider why it did things the way it did, the same factors might not apply in your case or the old code is simply bad. Still it's  a way of moving forwards if you otherwise wouldn't know how to approach it.
*  Come up with a plan for things that need to be done and discuss it here. Just because something was mentioned in issue description doesn't necessarily means that it is still relevant or good feature. 
*  When code changes are done and you are ready for PR, please follow the PR template.

"Test plan (required)" really means that. If those are GUI changes make a screenshot.
Make a basic list of steps for checking that changes are working as expected. This also a good point to consider any potential edge cases or different kind of interesting inputs if you didn't already do it while writing code. Actually perform the steps you described when making the PR even if they seem trivial and you did them during development, it helps catching any makes done during final cleanup and making sure you didn't forget anything.

**Comment by dhaval0894** [comment]
Hi, thanks a lot for taking the time to write down these steps. Also, sorry for the delayed response. I had got the build working and had also found the relevant source files. But I was trying to figure out the function that I can use to retrieve information from an `address`.  This is what I had planned:
1) Retrieve the information about the command using the `offset(address)`.
2) Using the command values to differentiate whether the string definition is defined or not and consequently, show/hide the remove option.

Sorry if this isn't right or If I have misunderstood something.

**Comment by dhaval0894** [comment]
Hi @karliss, I have implemented this in the same way `canCopy` is implemented. It toggles the visibility of the remove action depending upon the other actions:

- For `on_actionSetAsString_triggered()` and `on_actionSetAsStringAdvanced_triggered()`, it would set its visibility to true.
- For `on_actionSetAsStringRemove_triggered()` and `on_actionSetToCode_triggered()`, it would set its visibility to false.

I'm not sure whether this would be the right way of implementing this. It would be great if you can provide some feedback. I can raise the PR if that makes things more clear

**Comment by karliss** [comment]
Yes, for small changes like this and if you already implemented it's better to just create a PR than trying to describe code using text. Situation is a bit different  with larger changes  where doing wrong implementation would waste a lot of time.

**Comment by dhaval0894** [comment]
Hi @karliss, I have raised the PR. Please take a look whenever you get a chance.
