### ISSUE TITLE
Vmware Localhost Connect GDB

### ISSUE THREAD

**Issue by maskelihileci** [radareorg/cutter#2072]
Hello 

I am trying to connect to vmware I am getting ip not found error

Type : GDB
IP : localhost
Port : 8864

Note : I can connect with IDA Pro Software

**Comment by maskelihileci** [comment]
192.168.1.26 

I tried this again it was not connected

I can connect with IDA Pro Software

**Comment by ITAYC0HEN** [comment]
Hi, thank you for opening an issue :)
Seems like you didn't fill the issue template and thus, your issue is lacking important information we need to know.
Please fill the issue with al the detailed and relevant information so we will be able to fully help you.
Attach files, screenshots and reproducers if you can.

Thanks!

**Comment by XVilka** [comment]
Have you tried 127.0.0.1?
Most likely it's radare2 and host/name resolution problem. I bet it's Windows

**Comment by ITAYC0HEN** [comment]
Please make sure to use an IP address (127.0.0.1) and not a string ("localhost").

Since no answer was received from @maskelihileci in the last two weeks, and since crucial information wasn't provided to us and because the Issue template was not filled at all, I am closing this issue.

We will be happy to re-open this issue if you'll provide us with more information. Thank you!
