### ISSUE TITLE
Register view shows incorrect value if it's 64-bit integer

### ISSUE THREAD

**Issue by Jinmo** [radareorg/cutter#2108]
**Environment information**
* Operating System:Windows
* Cutter version:1.10.2
* Obtained from:
  - [x] Built from source
* File format:N/A

**Describe the bug**

Cutter uses drj command to obtain the values of registers, but if the value is larger than 2^52, it becomes broken because it cannot be expressed as a double value. e.g.

```
mov rax, 0x4141414141414141
```

Then cutter will show rax = 0x4141414141414000, even though drj shows the correct value.

**To Reproduce**

1. Open shellcode `48B84141414141414141`
2. Start emulation
3. Step one instruction
4. rax is shown as 0x4141414141414000.

**Expected behavior**

rax should be shown as 0x4141414141414141.

**Screenshots**

**Additional context**

I guess this is related with [QTBUG-28560](https://bugreports.qt.io/browse/QTBUG-28560), and it's fixed in Nov 2019, so upgrading the version of Qt might help, but not sure if it's best.

**Comment by karliss** [comment]
Looks like the qt changes have been merged in their dev branch but not 5.14 or 5.15.

**Comment by ITAYC0HEN** [comment]
Is it a pure Qt issue or can we overcome this?

**Comment by Jinmo** [comment]
Cutter currently uses Qt's parser(QJsonDocument) to parse JSON values from radare2.
In current version of qt, the value is converted to double just after parsing. Perhaps another parser can be used?

**Comment by ITAYC0HEN** [comment]
@yossizap can you have a look?

**Comment by int3rsys** [comment]
Happens to me as well with version 1.10.1 while using the lodsq instruction. The value is not fully loaded into the register, i.e: the lower end of the register filled with garbage

**Comment by karliss** [comment]
The possible approaches for fix:
* wait for qt patch to be included in official release - it's in the dev branch and will probably be included in Qt6 which will come out at the end of 2020. Not sure if they will merge it in 5.15 or not.
* merge the qt 64bit patch in cutter-deps - the problem will still affect Cutter linked against system Qt and people who compile Cutter themselves
* switching json parser - that's a significant amount of work, especially knowing that upstream Qt has fixed it
* modify r2 to pass 64 bit values as string instead of integer - I have seen this being done for some of r2 json commands. Downside is that it makes the api worse for other use cases like r2pipe+python  which is probably not  be affected by this problem as python has arbitrary size integers. Maybe it could be an r2 option for how the 64 bit integers are printed in json.
* workaround the Qt json parser API and obtain the value as string and parse it ourselves - depending on Qt json parser architecture and when it performs number parsing this might be impossible.

**Comment by karliss** [comment]
For now implemented solution which uses  r2 command that returns values as strings. After thinking this more I noticed that even with different Json parser or the fix in Qt json parser they would unlikely handle >64bit registers.

Related but slightly different case is 64 bit numbers everywhere else in r2<-> cutter data exchange. Created a separate issue for that #2142.
