### ISSUE TITLE
Reorder registers

### ISSUE THREAD

**Issue by Misiur** [radareorg/cutter#2139]
**Environment information**
* Operating System: Windows 10 home x64
* Cutter version: v1.10.3x64
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository

![](https://i.imgur.com/MrWAJwv.png)

Order of registers is ugly, it should go the normal way starting with `rax` on left column, or add the possibility to reorder them

**Comment by ITAYC0HEN** [comment]
Agree :) Thank you

**Comment by karliss** [comment]
Looks like `drj` returns them in expected order but since the json parser puts them in an ordered dictionary they get sorted alphabetically. `drrj` returns an array instead of object/dictionary so it should be usable for getting correct order. It seems to currently include some unexpected terminal escape codes, those would have to be fixed first.
