### ISSUE TITLE
"No decompiler available"

### ISSUE THREAD

**Issue by jos128** [radareorg/cutter#2188]
**Environment information**
* Operating System: Ubuntu 20.04 LTS
* Cutter version:Version 1.10.1, using r2-4.2.1
* Obtained from:
  - [ ] Built from source
  - [ ] Downloaded from release
  - [x] Distribution repository
* File format:

**Describe the bug**

Decompiler windows reads: "No Decompiler available." There is no decompiler to select. 

**To Reproduce**

1. Windows->check Decompiler

**Expected behavior**

I guess, get the decompiler.

**Comment by karliss** [comment]
Cutter developers have no control over what plugins  distribution package maintainers include. If you want a decompiler from the distribution package ask your distribution package maintainers to compile it.

Otherwise you can either use the Appimage build from Cutter release page which includes ghidra and r2dec, or compile the decompiler plugin yourself.

**Comment by jos128** [comment]
Thank you. With the Appimage everything works fine.
