### ISSUE TITLE
Insert new instructions

### ISSUE THREAD

**Issue by RazviOverflow** [radareorg/cutter#2269]
Hi everybody, 

How can we insert new instructions with Cutter when patching a binary? I don't mean nopping or editing the existing instr/bytes, I mean adding new ones without overwriting, so everything should move the corresponding offsets.

In the context menu (Right click - Edit) there's not such option.
![image](https://user-images.githubusercontent.com/41084837/85940337-f5f5be80-b91b-11ea-9640-255b6bd0d1e6.png)

Also I thought about increasing the size of .text section so there's room for new instructions, but I don't seem to find the option either. 

![image](https://user-images.githubusercontent.com/41084837/85940595-9dbfbc00-b91d-11ea-8b0d-cc9b19b77084.png)

**Comment by karliss** [comment]
In general case shifting things in an executable file is very hard problem. It would require perfectly identifying and updating all the cross-references and address calculation. Missing just few of them could easily cause the executable crash. The same applies to resizing .text section increasing it's size would mean moving all the following sections like rodata and change the relative positioning of code and data.

The typical approach to deal with this is to insert a jump in the place you are modifying. Jump to modified piece of code, execute the modified piece of code, jump back to original code. Depending on amount of modifications you want to make the gaps between functions or unimportant string literals might have enough space. If you want to add a lot of code a better approach would be modify the executable headers so that it loads additional dynamic library.

You might also be interested in dynamic instrumentation tools like Frida, DynamoRIO or intel pin tool.
