### ISSUE TITLE
Maximizing the Cutter in WSL2 crashes it.

### ISSUE THREAD

**Issue by michalani** [radareorg/cutter#2452]
* Operating System:
Windows 10 running cutter via WSL2
* Cutter version: v1.12.0
* Obtained from:
  - [x] Downloaded release from Cutter website or GitHub 
https://github.com/radareorg/cutter/releases/download/v1.12.0/Cutter-v1.12.0-x64.Linux.AppImage
**Describe the bug**
Clicking the maximize icon on the app crashes it.

**To Reproduce**

1. Install WSL2 on windows
2. Install cutter on WSL2
sudo curl -L https://github.com/radareorg/cutter/releases/download/v1.12.0/Cutter-v1.12.0-x64.Linux.AppImage -o /usr/bin/cutter && sudo chmod +x /usr/bin/cutter
4. sudo cutter --appimage-extract
cd into usr/bin/ of the install.
5. install important libraries
 sudo apt install build-essential cmake meson libzip-dev zlib1g-dev qt5-default libqt5svg5-dev qttools5-dev qttools5-dev qttools5-dev-tools libmagic-dev libgvc6 libgraphviz-dev libkf5syntaxhighlighting-dev python3-setuptools liblz4-dev libcapstone-dev libssl-dev libxxhash-dev libuv1-dev
6. Set up X11 forwarding server on windows such as XMing
7. set "export DISPLAY=ip:0" in WSL
8. Open Cutter
9. Maximize it.

**Expected behavior**
Should go full screen.

**Comment by karliss** [comment]
Unpacking appimage and afterwards overwriting libraries with system one seems like a strange thing to do. I wouldn't be surprised if one of them isn't perfectly binary compatible with versions originally bundled within appimage and against which the appimage is compiled, thus causing a crash.

The whole point of Appimage is to be mostly self contained and not to use system libraries. If you want to use system libraries instead of Appimage you should compile Cutter against them.

**Comment by ITAYC0HEN** [comment]
Hey! Thanks for opening this issue. I don't think we ever tried Cutter on WSL and it is a very nice experiment. 
I agree with Karliss. Appimage should be self contained and we can expect Cutter not to work properly when it tries to use system binaries instead of the bundled ones. Let us know if you experience other issues,

As such, this is not something we can help with. Please let us know if you have other questions, and keep us updated on whether you were abloe to execute Cutter on WSL2, that's very interesting :)

Cheers!
