### ISSUE TITLE
Add retdec-r2plugin to linux appimage

### ISSUE THREAD

**Issue by crass** [radareorg/cutter#2454]
The [retdec-r2plugin](https://github.com/avast/retdec-r2plugin) looks awesome and is not included in the most recent v1.12 appimage.  I was going down the path of trying to compile the native plugin using the libs installed in appimage, but that's a big PITA because there's no radare2 headers or pkgconfig files in the appimage.  It would be nice to have this plugin included like the ghidra one.

**Comment by ITAYC0HEN** [comment]
Hey @crass, thank you for opening this issue!
Indeed, the retdec plugin is dear to our heart as it is a very nice decompiler that works well with Cutter. Sadly, shipping the Retdec plugin bundled with our releases will reuqire us to ship its dependencies as well. If you installed r2retdec, then you know it requires a few gigabytes as it relies on LLVM. This will make our AppImage files few gigabytes of size which is not something we will do.
In addition, the are still LLVM conflicts with most Linux GPU drivers, a problem that hasn't been resolved.

Overall, and due to the point I raised above, and additional ones, we will not add the plugin to the Linux appaimge or othe releases. In the future, we might consider building the plugin against Cutter and offer it as a seperate download -- but this as well is not easy to do.

We will always be happy to support and guide users towards installation of the plugin so let us know if you have any question regarding this :)


At this time, I will close this issue, Thank you again!

cc @re-fox
