### ISSUE TITLE
Rewrite DisassemblyWidget

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#272]
Get rid of QPlainTextEdit. Why?
- https://github.com/radareorg/cutter/issues/252
- https://github.com/radareorg/cutter/issues/248
- https://github.com/radareorg/cutter/issues/97
I think it would be much more usable, but it is not a simple or short task.
Also I think the current advantage of QPlainTextEdit is that the user can select and copy the disassembly.

**Comment by xarkes** [comment]
Since we use pdJ and agJ now I'm not sure this is a good idea anymore.

**Comment by thestr4ng3r** [comment]
For the current implementation, I think there would not be much benefit in replacing QPlainTextEdit. There are some issues that need small hacks and workarounds, like keeping the selection on scroll, but it's all doable imo.

I'm not sure if by replacing QPlainTextEdit, you also meant replacing the use of r2's disassembly printing functionality with a custom one for cutter. That indeed would probably not make much sense anymore after pdJ.
Especially because now additional metadata could easily be added to the lines returned by pdJ. For example, for cases like this, we could add some information to the json that says something like "this line is the indicator for flag_a", so we could let the user rename that exact flag in the right-click menu:
![flag_rename](https://user-images.githubusercontent.com/1460997/35776783-0d7cb8e0-09a3-11e8-8b6b-f283703b2e32.png)
Or for #252 it could say "this is just a bbline line" and we could skip that.

In the long run however, we should think about a new DisassemblyWidget (maybe not to replace the current one, but as an option) that does not always refresh the whole disassembly, but caches disassembly for the whole file and lets you scroll through it. Like Hopper does it for example:
![hopper_disasm](https://user-images.githubusercontent.com/1460997/35776825-c6d1d3d4-09a3-11e8-89e5-550483d809d4.png)
For something like this, especially if we also want to have additional stuff like the lines on the left to be drawn natively, to show breakpoints, etc. QPlainTextEdit will probably not be sufficient.
But of course, this is quite a big task to do and not trivial to do correctly at all. Especially if you think about at which offsets to start disassembling and when to update which parts of the disassembly.

**Comment by xarkes** [comment]
Ok so I'm closing this as we will eventually do it in a far future.
