### ISSUE TITLE
Move main widgets into an external library

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#467]
What about moving the main widgets (disassembly, graph, hexdump) into another library so we could provide a generic reverse engineering GUI library?

**Comment by thestr4ng3r** [comment]
Since I am planning to make a "CodeWidget", which is basically the replacement for QPlainTextWidget for Disassembly and should be a general widget that can be used to display arbitrary code while being explicit about where exactly it draws characters and stuff, this approach may be fitting.

Also, we could maybe directly share code with x64dbg.

**Comment by xarkes** [comment]
Yes cc @mrexodia

**Comment by xarkes** [comment]
Here's a hackmd to think about it. Feel free to add suggestions.
https://hackmd.io/XZsiLVQoTBKF2KLOATh4qA#

**Comment by ITAYC0HEN** [comment]
is this still planned? or we gave up on the idea

**Comment by a1ext** [comment]
IMO it is not worth to develop and maintain such library (this will require supporting it over the years).
