### ISSUE TITLE
Cutter Docker

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#503]
I know that we have `docker.sh` script to build Cutter under docker.
I've seen that someone created this repo: https://github.com/ps1337/cutter-docker
Is it worth keeping the docker.sh script or not?

**Comment by xarkes** [comment]
ping @danielhenrymantilla @ps1337

**Comment by ps1337** [comment]
Thanks for the ping.

I think it would be possible to merge both Dockerfiles to get the best of both:

- My Dockerfile installs QT easily using apt (that's why i chose ubuntu:rolling)
- `docker.sh` brings additional Xauth configuration which may prevent container breakouts (check this discussions for a reference: https://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container) which is good practice.
- `docker.sh` allows mounting a single binary as read only into the container. This can be included in a Makefile to separate it from the Dockerfile or run script. Usage would be like `make run <binary>` to inspect a single binary.
- We could implement UID mapping (similar to `docker.sh`) but on run time rather than on image build time for additional compatibility

Let me know what you think.

**Comment by xarkes** [comment]
My main concern is that I don't want to maintain the Dockerfile myself, and I think that having twice the same thing (Dockerfile) is not necessary.
If you often update your repository, I think that linking it in the README is enough (and removing our docker.sh file)

**Comment by Maijin** [comment]
Then yeah maybe @ps1337 can maintain it here so we can avoid having 2 repository 👍

**Comment by danielhenrymantilla** [comment]
@ps1337's work is cleaner and more maintainable so I agree with all your suggestions.

The only thing is:
>  - We could implement UID mapping (similar to `docker.sh`) but on run time rather than on image build time for additional compatibility.

That would be great but a uid/gid pair still needs to be hardcoded for the guest (docker) user. When running the container with a shared mounted binary, that binary will have its uid and gid from the host user, which may no match (allow read access to) the ones set at build time (unless the guest user is `root:root`, which I don't recommend doing since it will be running an X application).

After some searching, there seems to be a way to do this with a custom entrypoint that dynamically creates the user at run-time. See https://github.com/tianon/gosu and https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by ps1337** [comment]
@Maijin: Sounds good.

@danielhenrymantilla: Thanks for the research, I'll consider this for my next update.

**Comment by xarkes** [comment]
So if I understood correctly, you will drop your repository, and make a pull request here?

**Comment by ps1337** [comment]
Correct, I'll try to get this done before the weekend begins

**Comment by ps1337** [comment]
Sent PR #534.

Please check the note on referencing/adding the files.
