### ISSUE TITLE
Remove QWebEngine dependency

### ISSUE THREAD

**Issue by mrexodia** [radareorg/cutter#57]
It takes a load of space (~80mb) in the release...

Widgets still using QWebEngine:

- [ ] Dashboard
- [ ] PreviewWidget
- [ ] SidebarWidget

----
- [ ] Remove from Travis 
- [ ] Remove from Appveyor

**Comment by xarkes** [comment]
Maybe can you have a look at it @thestr4ng3r ?

**Comment by thestr4ng3r** [comment]
I just notices we are including QtWebEngine, which is only for QML, in addition to QtWebEngineCore and QtWebEngineWidgets, which are the ones we need. I don't know how much this affects the size, but it can be removed right away.

SidebarWidget only shows some diagrams which are completely unnecessary imo, so that could just be removed.

Dashboard also shows unnecessary diagrams, that could be removed as well.

PreviewWidget has the mini graph, which I think can be removed too, because you could just dock the regular graph next to disassembly and zoom it out (when that is supported).

If you are ok with all those removals, I will do it.

**Comment by xarkes** [comment]
Sounds good to me!

**Comment by thestr4ng3r** [comment]
If we want any diagrams later, we should take a look qt QtCharts or something else based on QGraphicsWidget. Should be much more lightweight. https://doc.qt.io/qt-5/qtcharts-overview.html

**Comment by Maijin** [comment]
Great!

**Comment by resetnow** [comment]
Regarding the preview widget: since viz.js is just graphviz compiled to JS, it can be replaced fairly straght forward with a native call: https://github.com/mdaines/viz.js/blob/master/src/viz.c#L31

The question is, how should the dependency be handled? Is depending on system libgvc ok?

**Comment by thestr4ng3r** [comment]
In #60, the minigraph in the PreviewWidget is already completely removed including viz.js, so that is not relevant anymore.

**Comment by resetnow** [comment]
Is it going to be replaced or just removed?

**Comment by Maijin** [comment]
As said, It's not relevant.

**Comment by thestr4ng3r** [comment]
Completely removed. As I mentioned above, you could just dock the regular graph next to disassembly and zoom it out to have the same functionality.
