### ISSUE TITLE
Can't open file with utf8 chars in name

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#589]
I have been reported that files containing utf8 characters in their name cannot be loaded in Cutter (Windows).
I tried it with master on Linux and it works, although there are some issues:
![2018-07-23-114648_274x61_scrot](https://user-images.githubusercontent.com/10772605/43070000-ded5f6b8-8e6e-11e8-9b8c-497b9cbeb317.png)

**Comment by pelijah** [comment]
What do you mean under "cannot be loaded in Cutter"? Does it crash?

**Comment by xarkes** [comment]
It says "File not found" or similar error.

**Comment by pelijah** [comment]
Hmm my Cutter can open files with names that contains Unicode characters.

**Comment by xarkes** [comment]
cc @XVilka 
Amyway I think there's the display info that is still wrong in the Dashboard

**Comment by ITAYC0HEN** [comment]
Verified on Windows 64bit release:
![image](https://user-images.githubusercontent.com/20182642/46000209-9ddbb980-c0b0-11e8-97a1-3156493062f3.png)

**Comment by a1ext** [comment]
will try to fix it

**Comment by ITAYC0HEN** [comment]
Great! Thank you :)

**Comment by xarkes** [comment]
What's your status on it @a1ext ?

**Comment by a1ext** [comment]
Hi @xarkes, I'm trying to deal with this problem from different sides. 

The goal is to supply an ANSI encoded multi-byte string to an `open` function (it is being called when you call `r_core_file_open` -> `r_sandbox_open` -> `open`). This API is deprecated in MSVC 2017 (!!!).
![image](https://user-images.githubusercontent.com/14978853/47319768-3d607d80-d658-11e8-8fa1-b314b6b10455.png)

(Tried to rename `open` with `_open`, but unfortunatelly this didn't work.)

I can explain my trials:

1.  get the `System` text codec, encode every path which goes to r2 API call with this codec:
```cpp
bool CutterCore::loadFile(QString path, ut64 baddr, ut64 mapaddr, int perms, int va,
                          bool loadbin, const QString &forceBinPlugin)
{
    CORE_LOCK();
    RCoreFile *f;
    r_config_set_i(core_->config, "io.va", va);

    const QByteArray &baPath = qhelpers::nativeFromString(QDir::toNativeSeparators(path)); // << this guy

    f = r_core_file_open(core_, baPath.constData(), perms, mapaddr);
    if (!f) {
        eprintf("r_core_file_open failed\n");
        return false;
    }
```

where `qhelpers::nativeFromString` is:
```cpp
namespace {

constexpr char kSystemLocaleName[] = "System";

}

QByteArray nativeFromString(const QString &s)
{
    return QTextCodec::codecForName(kSystemLocaleName)->fromUnicode(s);
}

QString stringFromNative(const QByteArray &ba)
{
    return QTextCodec::codecForName(kSystemLocaleName)->toUnicode(ba);
}

```
This means we put already encoded multi-byte string to r2. This works, but this is not conforms that r2 expects every string is passed is being encoded in utf8, so some of points in cutter have to be additionally fixed, like the following:
![image](https://user-images.githubusercontent.com/14978853/47318521-f2913680-d654-11e8-8432-b1005ec192e6.png)

 I don't like this solution at all

2. Set `utf-8` locale at the app start and leave everything as is.
```cpp
#ifdef Q_OS_WIN
    char* setloc_rv = std::setlocale(LC_ALL, "en_US.utf8");
    qDebug() << "CutterApplication(): setlocale() = " << (setloc_rv ? setloc_rv : "failed");
```

Expected to work, but as I've seen during testing, its behavior is unstable, below are the fail table:

| OS    | Build type | Runtime link type | Does it work? |
| --- | --- | --- | --- |
| Windows 7 x64 | Release | shared | no (default configuration of Cutter) |
| Windows 7 x64 | Debug | shared | yes |
| Windows 7 x64 | Release | static | yes |
| Windows 10 x64 | Release | shared | yes |
| Windows 10 x64 | Debug | shared | yes |

This solution cannot be used because of different behavior of MSVC 2017 shared CRT.

3. Make fixes in radare2. First of all enable `_UNICODE` and `UNICODE` defines when building r2 (because Cutter is also have them). Fix the rest places which uses functions like `open` for file access - that is under development. The hardest part is to not break the r2 code for other systems.

P.S. If I compile r2 with unicode support and open unicode-named file with `w32` IO it opens the file, but then, internally it is being reopened with bad name and the following analysis fails at all:
![image](https://user-images.githubusercontent.com/14978853/47321092-40f60380-d65c-11e8-83b9-887a35789a8a.png)

So, I'm not give up and continue trying the third approach. If you have any hints - would be good :)

**Comment by a1ext** [comment]
Also, I think the rest of IOs have to be checked and fixed as well...

**Comment by a1ext** [comment]
Seems like we are almost done with this, need to do some testing, PR to `radare2` and then PR here.
![image](https://user-images.githubusercontent.com/14978853/47467930-45a7ec80-d801-11e8-9872-28b713f8042e.png)
