### ISSUE TITLE
Background color in themes is not supported

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#634]
and this makes many r2themes look bad in cutter

This is `bold` for example: (check the CALLs)

<img width="1188" alt="screen shot 2018-08-18 at 13 17 04" src="https://user-images.githubusercontent.com/6431515/44298753-0765ec80-a2e9-11e8-8401-94a0d078ffe0.png">

**Comment by xarkes** [comment]
That's intended and I don't know if we want to change that or not.

**Comment by radare** [comment]
another option is to use the bg highlight value if any instead of the foreground. that will solve the visual problems because of the contrast with the expected dark background.

And yes, most r2 themes look bad in cutter, and i think we should split them between black and white themes. so cutter can reduce the list depending if running in dark or not dark modes

**Comment by ITAYC0HEN** [comment]
highlight\background  color for specific lines won't be implemented but pancake's suggestion for different Color Themes for dark\light modes is great.

I summed it up in a dedicated issues: #816 

Closing this
