### ISSUE TITLE
Allow to override ESIL code for particular opcode

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#698]
Provide an option to override ESIL for particular opcode, maybe in a context menu?

**Comment by Maijin** [comment]
Yes like the immediate change

**Comment by ITAYC0HEN** [comment]
what's that?

**Comment by ITAYC0HEN** [comment]
what's that? a detailed example with r2 would help a lot

**Comment by ITAYC0HEN** [comment]
@xvilka what is this?

**Comment by XVilka** [comment]
Hm? I thought it is obvious - to be able to change the ESIL representation for this particular instruction in that particular place.

**Comment by ITAYC0HEN** [comment]
is this a radare2 command? is it documented? how is it done? why is this necessary for cutter?

**Comment by radare** [comment]
ahe for esil

**Comment by radare** [comment]
anal hints

**Comment by Maijin** [comment]
that's useful for emulation yes

**Comment by ITAYC0HEN** [comment]
Hi, thank you for opening an issue :)
Seems like this issue does not have a detailed explanation and thus, your issue is lacking important information we need to know. After several questions, the usage, the need, and the solution **still** aren't clear - and it should be clear to any potential contributor.

Please fill the issue template with all the detailed and relevant information so we will be able to fully help you.
Attach files, screenshots, links, and examples if possible.


Thanks!

**Comment by condret** [comment]
I suggest you to close this @radare / @trufae already answered this: Use anal-hints (see ah?)

**Comment by Maijin** [comment]
Closed and replaced with https://github.com/radareorg/cutter/issues/2252
