### ISSUE TITLE
Add anal.in in Advanced Analysis

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#875]
**Is your feature request related to a problem? Please describe.**
To select a particular zone to analyze

**Describe the solution you'd like**
Add anal.in selector in advanced analysis (similar to #395, #873)

**Comment by Maijin** [comment]
ping @ITAYC0HEN

**Comment by ITAYC0HEN** [comment]
I think that `anal.in` options can also be added to the Preference widget if users want to modify it after the initial analysis (I wanted to do this now and had to used radare2 commands)

**Comment by ocastejon** [comment]
I'd like to work on this issue since it is related to the analysis section in the preferences widget (see PR #2332). 

I see that the search widget has a similar option (for `search.in`), but not all of the possible values are included in the selector. Is it for a particular reason? In this case, do you think the values for `anal.in` should be also limited?

**Comment by ITAYC0HEN** [comment]
Yeah because search.in has so many options that aren't really useful for GUI users and it becomes too much. 

I think it is the same for analysis, just need to think about the ones we want to keep
