### ISSUE TITLE
Add more columns in the Sections panel

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#928]
* Add Permissions column (rwx)
* Add context menu to copy name or address / end address into clipboard
* Add column showing md5/sha1/... (configurable see https://github.com/radareorg/cutter/issues/925
* Ordinal
* Add hvaddr?

**Comment by zoyron** [comment]
Greetings @ITAYC0HEN,  I would like to work on this issue. Kindly guide me through the process of contributing to this issue. Thank you.

**Comment by karliss** [comment]
Hi, new developers are always welcome.

I don't know your experience level so don't mind if some of the steps seem obvious.

* Start by reading this https://cutter.re/docs/code.html
* See https://github.com/radareorg/cutter/blob/master/docs/source/building.rst for compilation instructions
* Get the build working
* Run cutter and get familiar with how the sections widget looks currently
* Find the the source files implementing sections widget
* If necessary read https://doc.qt.io/qt-5/model-view-programming.html for basic understanding of how Qt model system works. It will be necessary for adding more columns.
* Come up with a plan for things that need to be done and discuss it here. Just because something was mentioned in issue description doesn't necessarily means that it is still relevant or  good feature.
* When code changes are done and you are ready for PR, please follow the PR template.

"Test plan **(required)**" really means that.  If those are GUI changes make a screenshot. 
Make a basic list of steps for checking that changes are working as expected. This also a good point to consider any potential edge cases or different kind of interesting inputs if you didn't already do it while writing code. Actually perform the steps you described when making the PR even if they seem trivial and you did them during development, it helps catching any makes done during final cleanup and making sure you didn't forget anything.


Feel free to ask questions in cutter telegram or IRC to get you started faster although some of the questions specific to this issue might be better discussed here.

**Comment by ITAYC0HEN** [comment]
Hey @zoyron , still want to give this one a chance?

**Comment by ITAYC0HEN** [comment]
This is mostly done by now. The important things were implemented..
Thank you! Closing
