### ISSUE TITLE
cutter.exe is not a valid Win32 application

### ISSUE THREAD

**Issue by Reg1nleifr** [radareorg/cutter#978]
**Environment information**
* Operating System: Windows XP, SP3
* Cutter version: 1.1-1.7.2
* File format: 32 bit

**Describe the bug**
It seems like Windows XP doesn't like the executable format. Whenever I try to open cutter.exe it keeps telling me that it is not a valid Win32 application. Tried different versions (1.1, 1.6, 1.7.2, Current Pre-Release)

**To Reproduce**
1. Get a Win XP SP3 VM 
2. Drag the win32 zip into the machine
3. Try to start cutter
4. :(

**Expected behavior**

**Screenshots**

<img width="952" alt="screen shot 2018-12-03 at 12 29 20 am" src="https://user-images.githubusercontent.com/14288972/49345828-e99f7600-f692-11e8-99f7-174425669869.png">

**Additional message**
Thanks for the great product, I've been using it on my personal notebook and it worked like a charm, however I'd need it for some 32 bit reversing on a XP Machine :)

**Comment by ITAYC0HEN** [comment]
Windows XP is not supported by Cutter so we would not be able to solve this issue. That said, theoretically, it should be possible to compile Cutter to fit XP as well and you can give it try.

On a personal note here, as a malware researcher, I'd suggest giving up on Windows XP entirely and move to Windows 10 since the vast majority of the malware would be able to be executed there successfully. Windows 7 is a nice compromise.

Closing this issue

**Comment by Reg1nleifr** [comment]
Great thanks I'll give compiling a shot and consider moving forward thanks for the advice!
